### ISSUE TITLE
Service error

### ISSUE THREAD

**Issue by ghost** [kylekatarnls/jade-symfony#1]
I'm having this error with PHP7 / symfony 3.0:

FatalErrorException in PugSymfonyEngine.php line 7:
Compile Error: Cannot declare class Pug\JadeSymfonyEngine because the name is already in use

**Comment by qsollet** [comment]
Try to update the package

JadeSymfonyEngine is not being declared in PugSymfonyEngine.php.

If this does not work I would recommend to use pug-symfony package as Jade changed it's name to Pug (https://github.com/pugjs/pug)

**Comment by kylekatarnls** [comment]
Hi, [pug-php/pug-symfony](https://github.com/pug-php/pug-symfony) is the official repository now, but I still keep up to date **kylekatarnls/jade-symfony** as a mirror. So it's recommanded to use **pug-php/pug-symfony** but it's not yet needed, a simple `composer update` should fix it. Do you still get this error with the last version?

**Comment by ghost** [comment]
Hello

thanks for the answer

I updated it and now i'm having the following error:

 [LogicException]  
 The following loader(s) are not registered: pug

**Comment by kylekatarnls** [comment]
Hello,

It seems the config is not aligned with the file extension you use:

If you use **.pug** file extension, update **services.yml** and **config.yml** to the new values (with Pug):
https://github.com/pug-php/pug-symfony#install

If you want to keep **.jade** file extension, use the old settings:
https://github.com/kylekatarnls/jade-symfony/tree/1.2.0#install

You can also use both extensions with:

**app/config/services.yml**:

``` yaml
services:
    templating.engine.pug:
        class: Pug\PugSymfonyEngine
        arguments: ["@kernel", "@templating.helper.assets", "@templating.helper.router"]
    templating.engine.jade:
        class: Jade\JadeSymfonyEngine
        arguments: ["@kernel", "@templating.helper.assets", "@templating.helper.router"]
```

and **app/config/config.yml**:

``` yaml
...
    templating:
        engines: ['pug', 'jade', 'twig', 'php']
```

I'm sorry about all the disturbance, the jade name change was a real brain teaser.
