### ISSUE TITLE
assets:publish failure Undefined index error

### ISSUE THREAD

**Issue by mertoksuz** [kylekatarnls/jade-symfony#2]
after composer install, when you try to use `assets:publish` command you will get;

`[Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: assets `

**Comment by kylekatarnls** [comment]
Maybe you miss the bundle deployment step: https://github.com/kylekatarnls/jade-symfony#deployment

**Comment by mertoksuz** [comment]
i already add that part, cleared caches but still same

**Comment by kylekatarnls** [comment]
OK, I start inspecting, just one more thing to be sure, you use Symfony 3?

**Comment by kylekatarnls** [comment]
Issue confirmed. There is a regression. I'm working on it.

**Comment by mertoksuz** [comment]
yes i am using symfony3, thanks.

**Comment by kylekatarnls** [comment]
I'm not sure yet of the root cause but the following work-around worked for me:

Add:
```yaml
services:
    templating.engine.pug:
        class: Pug\PugSymfonyEngine
        arguments: ["@kernel"]

```
in your **config.yml**, then remove **var/cache** directory, then re-enter the command:
```shell
php bin/console assets:publish --env=prod
```

Is it working for you?

**Comment by mertoksuz** [comment]
**app/config/services.yml**
```yml
services:
    templating.engine.pug:
        class: Pug\PugSymfonyEngine
        arguments: ["@kernel"]
```
`php bin/console assets:publish --env=prod`

```
Type error: Argument 1 passed to Jade\Symfony\Css::__construct() must be an instance of Symfony\Bundle\FrameworkBundle\Templating\He  
  lper\AssetsHelper, null given, called in /var/www/jade/vendor/pug-php/pug-symfony/src/Jade/JadeSymfonyEngine.php on line 160
```
